server:
  port: 8083

spring:
  application:
    name: notification-service

  rabbitmq:
    password: password
    username: user
    host: localhost
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

discord-api:
  base-url: https://discord.com/api

api-key: fu1IGDv9DSgQXyJm1FIue0f3MvWgxskdOZ3iX3cROW9PXbCEQpYZclpsD5lULggqFk5eOGHGtYw2r975hpUICLPfrm8UAjFWosUG