version: '3.8'

services:
  schedule-service-postgres:
    container_name: 'schedule-service-postgres'
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: schedule-service
    ports:
      - '5432:5432'

  keycloak-postgres:
    container_name: 'keycloak-postgres'
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: keycloak
    ports:
      - '5433:5432'

  rabbitmq:
    container_name: 'rabbitmq'
    image: rabbitmq:3.11.7-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - '5672:5672'
      - '15672:15672'

  keycloak:
    container_name: 'keycloak'
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_DATABASE: keycloak
      DB_USER: root
      DB_SCHEMA: public
      DB_PASSWORD: root
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - '8000:8080'
    depends_on:
      - keycloak-postgres
    command:
      - start-dev

  discovery-server:
    container_name: 'discovery-server'
    build:
      context: discovery-service
      dockerfile: Dockerfile
    ports:
      - '8761:8761'

  discord-webhooks-mongo:
    container_name: 'discord-webhooks-mongo'
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: discord-webhooks-service
    ports:
      - '27017:27017'