version: '3.8'

services:
  schedule-service-postgres:
    container_name: 'schedule-service-postgres'
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: schedule-service
    ports:
      - '5432:5432'

  course-service-postgres:
    container_name: 'course-service-postgres'
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: course-service
    ports:
      - '5434:5432'

  keycloak-postgres:
    container_name: 'keycloak-postgres'
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: keycloak
    ports:
      - '5433:5432'

  rabbitmq:
    container_name: 'rabbitmq'
    image: rabbitmq:3.11.7-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - '5672:5672'
      - '15672:15672'

  keycloak:
    container_name: 'keycloak'
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_DATABASE: keycloak
      DB_USER: root
      DB_SCHEMA: public
      DB_PASSWORD: root
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - '8000:8080'
    depends_on:
      - keycloak-postgres
    volumes:
      - ./keycloak/polsl-course-api-realm.json:/opt/keycloak/data/import/realm.json
    command:
      - start-dev
      - --import-realm

  discovery-server:
    container_name: 'discovery-server'
    build:
      context: discovery-service
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - '8761:8761'

  api-gateway:
    container_name: api-gateway
    build:
      context: api-gateway
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_NAME: discovery-server
      EUREKA_PORT: 8761
    ports:
      - '9090:9090'
    depends_on:
      - discovery-server