version: '3.8'

services:
  db:
    container_name: 'db'
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'