version: '3.8'

services:
  db:
    container_name: 'db'
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - '5432:5432'
  
  rabbitmq:
    container_name: 'rabbitmq'
    image: rabbitmq:3.11.7-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - '5672:5672'
      - '15672:15672'