version: '3.8'

services:
  schedule-service-postgres:
    container_name: 'schedule-service-postgres'
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: schedule-service
    ports:
      - '5432:5432'

  course-service-postgres:
    container_name: 'course-service-postgres'
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: course-service
    ports:
      - '5434:5432'

  keycloak-postgres:
    container_name: 'keycloak-postgres'
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: keycloak
    ports:
      - '5433:5432'

  discord-webhooks-mongo:
    container_name: 'discord-webhooks-mongo'
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: discord-webhooks-service
    ports:
      - '27017:27017'

  rabbitmq:
    container_name: 'rabbitmq'
    image: rabbitmq:3.11.7-management-alpine
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - '5672:5672'
      - '15672:15672'

  keycloak:
    container_name: 'keycloak'
    image: quay.io/keycloak/keycloak:latest
    restart: always
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-postgres
      DB_DATABASE: keycloak
      DB_USER: root
      DB_SCHEMA: public
      DB_PASSWORD: root
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - '8000:8080'
    depends_on:
      - keycloak-postgres
    volumes:
      - ./keycloak/polsl-course-api-realm.json:/opt/keycloak/data/import/realm.json
    command:
      - start-dev
      - --import-realm

  discovery-server:
    container_name: 'discovery-server'
    restart: always
    build:
      context: discovery-service
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - '8761:8761'

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    hostname: zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.4.3
    hostname: broker
    container_name: broker
    restart: always
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  akhq:
    image: tchiotludo/akhq:0.24.0
    container_name: my-akhq
    restart: always
    depends_on:
      - broker
    ports:
      - "8086:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          server:
            access-log: # Access log configuration (optional)
              enabled: true # true by default
              name: org.akhq.log.access # Logger name
              format: "[Date: {}] [Duration: {} ms] [Url: {} {}] [Status: {}] [Ip: {}] [User: {}]" # Logger format
          clients-defaults:
            consumer:
              properties:
                isolation.level: read_committed
          security:
            default-group: admin
          connections:
            local:
              properties:
                bootstrap.servers: "broker:29092"
          pagination:
            page-size: 25 # number of elements per page (default : 25)
            threads: 8 # Number of parallel threads to resolve page