server:
  port: 9090

spring:
  application:
    name: api-gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - url: /course-service/v3/api-docs
        name: Course Service
      - url: /schedule-service/v3/api-docs
        name: Schedule Service