server:
  port: 9090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: schedule-service
          uri: lb://schedule-service
          predicates:
            - Path=/api/schedules/**, /api/courses/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
