server:
  port: 8081

spring:
  application:
    name: web-scraper-service

  rabbitmq:
    password: password
    username: user
    host: localhost
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

plan-polsl-url: https://plan.polsl.pl/