spring:
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/polsl-course-schedule-api
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver