spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}/schedule-service
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    password: ${RABBITMQ_PASSWORD}
    username: ${RABBITMQ_USERNAME}
    host: ${RABBITMQ_HOST}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_URL}:8080/realms/polsl-course-api
          jwk-set-uri: http://${KEYCLOAK_URL}:8080/realms/polsl-course-api/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_NAME}:${EUREKA_PORT}/eureka
  instance:
    prefer-ip-address: true