spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL}/schedule-service
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    password: ${RABBITMQ_PASSWORD}
    username: ${RABBITMQ_USERNAME}
    host: ${RABBITMQ_HOST}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_NAME}:${EUREKA_PORT}/eureka