server:
  port: 8082

spring:
  application:
    name: discord-notification-service

  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: root
      database: discord-webhooks-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000/realms/polsl-course-api

  rabbitmq:
    password: password
    username: user
    host: localhost
    port: 5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

schedule-service:
  base-url: http://schedule-service

discord-api:
  base-url: https://discord.com/api