server:
  port: 8084

spring:
  application:
    name: web-scraper-service

  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: localhost:29092
    security:
      protocol: PLAINTEXT

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: w3c
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

plan-polsl-url: https://plan.polsl.pl/

kafka:
  observation:
    producer:
      enabled: true
    consumer:
      enabled: true
  topics:
    schedule-event: schedule.event
    course-raw: schedule.raw
    dlt: web-scraper-service.schedule.event.dlt
  config:
    back-off:
      max-retries: 2
      multiplier: 2.0
      interval:
        initial: 200
        max: 400

logging.pattern.level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"