server:
  port: 8080

spring:
  application:
    name: web-scraper-service

  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVER_HOST}:${BOOTSTRAP_SERVER_PORT}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_HOST}:${EUREKA_PORT}/eureka
  instance:
    prefer-ip-address: true

management:
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST}:${ZIPKIN_PORT}/api/v2/spans