server:
  port: 8083

spring:
  application:
    name: domain-model-mapper-service

  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: localhost:29092
    security:
      protocol: PLAINTEXT

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: w3c
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

kafka:
  observation:
    producer:
      enabled: true
    consumer:
      enabled: true
  topics:
    schedule-raw: schedule.raw
    schedule-domain: schedule.domain
    dlt: domain-model-mapper-service.schedule.raw.dlt
  config:
    back-off:
      interval: 0
      max-attempts: 0

logging.pattern.level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"