server:
  port: 8082

spring:
  application:
    name: discord-webhooks-service

  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: root
      database: discord-webhooks-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka