server:
  port: 8083

logging.pattern.level: "%5p [${spring.application.name},%X{traceId:-},%X{spanId:-}]"

spring:
  application:
    name: "webhook-service"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000/realms/polsl-course-api

  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    bootstrap-servers: localhost:29092
    security:
      protocol: PLAINTEXT

  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: root
      password: root
      database: webhook-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: w3c
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

keycloak:
  server-url: http://localhost:8000
  realm: polsl-course-api

schedule-service:
  base-url: http://schedule-service